# Generated by Django 4.1.3 on 2022-12-11 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0007_alter_profile_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='avatar',
        ),
    ]
