# Generated by Django 4.1.3 on 2022-12-17 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0010_profile_bookmarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='header',
            field=models.ImageField(default='default_avatar.jpg', upload_to='profile_images'),
        ),
    ]
