# Generated by Django 4.1.3 on 2022-12-18 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0012_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='default_avatar.jpg', upload_to='profile_images'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='header',
            field=models.ImageField(default='default_header.png', upload_to='profile_images'),
        ),
    ]
