# Generated by Django 4.1.3 on 2022-12-21 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0017_profile_joined'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='joined',
        ),
    ]
