# Generated by Django 4.1.3 on 2022-12-23 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0018_remove_profile_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='likes',
            field=models.IntegerField(default=None),
        ),
    ]
