# Generated by Django 4.1.3 on 2022-12-23 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0020_alter_message_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='image',
        ),
    ]
