# Generated by Django 4.1.3 on 2022-12-23 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0021_remove_message_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
