# Generated by Django 4.1.3 on 2022-12-24 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0023_message_dislikes_likedislike'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='profile_images'),
        ),
    ]
